package com.example.exchangeabletoken

class ActivityProductBinding {
companion object {
        fun getMarketData(): List<DataProduct> {
            return listOf(
                DataProduct(1, "Apple", 10, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(2, "Orange", 15, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(3, "Banana", 20, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(4, "Pineapple", 25, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(5, "Watermelon", 30, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(6, "Mango", 35, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(7, "Strawberry", 40, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(8, "Papaya", 45, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(9, "Grapes", 50, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(10, "Peach", 55, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(11, "Pear", 60, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(12, "Cherry", 65, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(13, "Pomegranate", 70, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(14, "Pomelo", 75, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(15, "Lemon", 80, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(16, "Lime", 85, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(17, "Coconut", 90, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(18, "Avocado", 95, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(19, "Raspberry", 100, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(20, "Blueberry", 105, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(21, "Blackberry", 110, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(22, "Cranberry", 115, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(23, "Kiwi", 120, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(24, "Guava", 125, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(25, "Jackfruit", 130, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(26, "Durian", 135, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(27, "Lychee", 140, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(28, "Mangosteen", 145, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(29, "Passion Fruit", 150, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(30, "Rambutan", 155, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(31, "Star Fruit", 160, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(32, "Tamarind", 165, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(33, "Watermelon", 170, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(34, "Cantaloupe", 175, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(35, "Honeydew", 180, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(36, "Cucumber", 185, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(37, "Tomato", 190, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(38, "Potato", 195, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(39, "Onion", 200, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(40, "Garlic", 205, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(41, "Carrot", 210, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(42, "Cabbage", 215, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(43, "Broccoli", 220, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(45, "Cauliflower", 225, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(46, "Spinach", 230, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(47, "Lettuce", 235, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(48, "Celery", 240, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(49, "Asparagus", 245, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(50, "Mushroom", 250, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(51, "Eggplant", 255, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(52, "Pumpkin", 260, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(53, "Zucchini", 265, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(54, "Corn", 270, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(55, "Peas", 275, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(56, "Bean", 280, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(57, "Sweet Potato", 285, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(58, "Yam", 290, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(59, "Turnip", 295, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(60, "Rutabaga", 300, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(61, "Radish", 305, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(62, "Beet", 310, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Fruit"),
                DataProduct(63, "Monkey", 315, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Monkey"),
                DataProduct(64, "Unicorn", 320, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Unicorn"),
                DataProduct(65, "Panda", 325, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Panda"),
                DataProduct(66, "Pig", 330, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Pig"),
                DataProduct(67, "Dog", 335, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Dog"),
                DataProduct(68, "Cat", 340, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Cat"),
                DataProduct(69, "Cow", 345, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Cow"),
                DataProduct(70, "Horse", 350, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Horse"),
                DataProduct(71, "Chicken", 355, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Chicken"),
                DataProduct(72, "Duck", 360, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Duck"),
                DataProduct(73, "Goat", 365, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Goat"),
                DataProduct(74, "Sheep", 370, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Sheep"),
                DataProduct(75, "Lamb", 375, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Lamb"),
                DataProduct(76, "Rabbit", 380, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Rabbit"),
                DataProduct(77, "Piglet", 385, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Piglet"),
                DataProduct(78, "Puppy", 390, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Puppy"),
                DataProduct(79, "Kitten", 395, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Kitten"),
                DataProduct(80, "Calf", 400, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Calf"),
                DataProduct(81, "Foal", 405, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Foal"),
                DataProduct(82, "Chick", 410, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Chick"),
                DataProduct(83, "Duckling", 415, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Duckling"),
                DataProduct(84, "Kid", 420, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Kid"),
                DataProduct(85, "Lambkin", 425, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Lambkin"),
                DataProduct(86, "Rabbit", 430, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Rabbit"),
                DataProduct(87, "Piglet", 435, "https://www.pngitem.com/pimgs/m/30-307416_transparent-apple-png-apple-fruit-png-download.png", "Piglet"),
            )
        }
    }
}
